name: PHP Coding Standards

on:
  push:
    branches:
<% branches.forEach((branch) => { -%>
      - "<%- branch %>"
<% }); -%>
    paths:
      - "**.php"
      - .github/workflows/php-coding-standards.yml
  pull_request:
    paths:
      - "**.php"
      - .github/workflows/php-coding-standards.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare PHP
        uses: woocommerce/grow-test/prepare-php@actions-v2
        with:
          php-version: <%= phpVersion %>
          tools: cs2pr

      - name: Log PHPCS information
        run: vendor/bin/phpcs -i

      - name: Run PHPCS on all files
        run: vendor/bin/phpcs ./* -q --report=checkstyle | cs2pr
